### PR TITLE
Feature/implement registration and invitation

### PR DESCRIPTION
**Pull request by Pe5h4**
Related seacat admin ui PR: https://github.com/TeskaLabs/seacat-admin-webui/pull/8

and related to fixes in SeaCat auth service https://github.com/TeskaLabs/seacat-auth/pull/134

### CODE REVIEW

**Comment by Pe5h4** [comment]
@ateska This PR is about 1st iteration implementation of invitation and registration, in this case for SeaCat **Auth** UI

- registration and invitation screens and cards were introduced
- in addition to this, I have updated the error responses in whole auth app as we spoke of about (prolonged the time of the alert message to 30s and display the whole message from error response)
- this PR is related to SeaCat Admin UI PR: https://github.com/TeskaLabs/seacat-admin-webui/pull/8
- and to SeaCat Auth service PR: https://github.com/TeskaLabs/seacat-auth/pull/134 where some additional fixes were made
- when user is logged in, then they can either `Accept invitation` or `Switch account`
- if they decided to `Accept invitation`, then they got the validation that everything went well and then redirected to the root of the application
- if they decide to `Swich account`, then they are redirected to a window where they can choose between login in to the app and then accept invitation, or they can fill the registration fields (those are rendered based on features which are coming from the service - so they are rendered dynamically (also with required, editable, and other features))
- When user fill their registration, then its again validated and then they are redirected to login page
- If the invitation became invalid, there is a card with some info message:
Selection_108

Here you can see the whole circle as it was also presented on review
invitation-registration

**Comment by ateska** [comment]
Looks very good to me.

I have these remarks:

- [ ] Texts needs to be polished to be more user friendly
- [ ] Whitespace around cards is still very small, it doesn't feel right

**Comment by Pe5h4** [comment]
> Looks very good to me.
> 
> I have these remarks:
> 
>     * [ ]  Texts needs to be polished to be more user friendly
> 
>     * [ ]  Whitespace around cards is still very small, it doesn't feel right

@ateska Sure.

About the padding - I just dont know how large we want to have it, since in this PR I have implemented the same padding to the card header as it is in the rest of our cards across the apps.

Here is the current state (in main branch):

Selection_110

Here is how it is in this PR:

Selection_112

Here is how it looks like if I will add even more padding to the card header:

Selection_113

Padding in card header and card body + card has been enlarged to cover more horizontal space:
Selection_115


Should be the padding implemented to the card as a whole, or just to the card header?

**Comment by ateska** [comment]
I propose to have a quick workshop in this next Tue. ok?

**Comment by Pe5h4** [comment]
> I propose to have a quick workshop in this next Tue. ok?

@ateska Sure, I will send an invitation (I think we can do it after the ws about investigation component;

Btw. after todays ws with Robin, we have come up with some minor updates (and also text polishing). The main feature is here collapsing / uncollapsing register/login card while on Register screen just to emphasize what is currently used and to diminish differences between cards content and its styling

registr-kolecko

register-invite-collapse

**Comment by Pe5h4** [comment]
@ateska Registration round with changes in SeaCat Auth UI as per reviews on workshops

- [x]  Polished text 

- [x] Cards refactored with more user friendly flow

registr-kolecko2

**Comment by Pe5h4** [comment]
@ateska ^^^

**Comment by Pe5h4** [comment]
Refactored error responses and again bit polished text as per fridays review

**Comment by Pe5h4** [comment]
@ateska Can you review pls?

**Review by ateska — APPROVED** [review]
Let's merge it ... but texts are still not aligned completely.
Specifically we are still using term "registered user" instead of "existing user" on more places.

Also fonts are still a bit random ... but it is definitively better that previous round.

**Comment by Pe5h4** [comment]
@ateska About `registered user` term - we dont use it there at all, it may be misleading since there is a gif image which has been created before the refactorisation of the texts

**Pull request merged**
